"""Assemble a paper-ready security-analysis report (markdown; IEEE TIFS structure).

Ties together NIST/TestU01 results, linear complexity, structural attacks,
forward/backward security, provable/PQ scaffolding, and the reference
comparison into a single document with placeholders for the human-written
proof parts (Tier 1/2 arguments).
"""

from __future__ import annotations

import os
from typing import Dict, Optional

from .comparison import CA_ATTACK_SURFACE, REFERENCE_CIPHERS

__all__ = ["build_report"]


def build_report(
    cipher_name: str,
    outdir: str = "results",
    battery: Optional[Dict] = None,
    lc: Optional[int] = None,
    lc_len: Optional[int] = None,
    stats: Optional[Dict] = None,
    ca_screen: Optional[Dict] = None,
    security: Optional[Dict] = None,
    fpga: Optional[Dict] = None,
) -> str:
    """Write ``results/report.md`` and return its path.

    All generated tables/figures are referenced by filename so the report stays
    in sync with ``report.py`` / ``comparison.py`` outputs.
    """
    os.makedirs(outdir, exist_ok=True)
    L: list = []
    add = L.append

    add(f"# Security Analysis Report: {cipher_name}")
    add("")
    add("> Generated by `stream-cipher-analyzer`. NIST SP 800-22 was **withdrawn** "
        "by NIST in Nov 2022; it is retained for convention and paired with TESTU01.")
    add("")

    # 1. Introduction & related work
    add("## 1. Introduction and Related Work")
    add("")
    add("Cellular-automaton (CA) stream ciphers trace back to Wolfram's rule-30 PRG "
        "(CRYPTO 1985) and were broken by Meier--Staffelbach (EUROCRYPT 1991, "
        "correlation-immunity failure) and Koc--Apohan (1997, low nonlinearity). The "
        "authoritative survey Mariot 2024 (arXiv:2405.02875) concludes rule 30 is "
        "*completely useless* for cryptography and catalogs the CA attack surface "
        "(Table \\ref{tab:ca_attacks}).")
    add("")
    add("**Known CA attack surface** (`ca_attack_surface.csv/.tex`):")
    add("")
    for e in CA_ATTACK_SURFACE:
        add(f"- {e['attack']} -> {e['consequence']} [{e['ref']}]")
    add("")

    # 2. Algorithm specification (placeholder)
    add("## 2. Algorithm Specification")
    add("")
    add("> *TODO (human): formalize the cipher as a map F : (K, IV) -> keystream; "
        "give the CA rule, neighborhood, boundary condition, key/IV loading, and "
        "keystream extraction.*")
    add("")

    # 3. Randomness & statistical analysis
    add("## 3. Randomness and Statistical Analysis")
    add("")
    if battery is not None:
        add("NIST SP 800-22 results (`nist_summary.csv/.tex`):")
        add("")
        add("| Test | pass rate | uniformity p |")
        add("|---|---|---|")
        for name, res in battery.items():
            add(f"| {name} | {res['pass_rate']:.3f} | {res['uniformity_p']:.3f} |")
        add("")
    if lc is not None:
        add(f"**Linear complexity** (first {lc_len or '?'} bits): {lc} "
            f"(random expectation ~{(lc_len or 0) // 2}). "
            "Figure: `linear_complexity.pdf`.")
        add("")
    if stats is not None:
        add(f"Monobit z = {stats['monobit']['z']:.3f}; runs z = {stats['runs']['z']:.3f}; "
            f"block chi-square p = {stats['block_chi_square']['p']:.3f}. "
            "Figure: `autocorrelation.pdf`.")
        add("")

    # 4. Structural cryptanalysis
    add("## 4. Structural Cryptanalysis")
    add("")
    if ca_screen is not None:
        add("Linear-degeneration screen (Berlekamp-Massey):")
        add("")
        for rule, r in ca_screen.items():
            add(f"- rule {rule}: LC = {r['linear_complexity']}, ratio = {r['ratio']:.3f}, "
                f"degenerate = {r['degenerate']}")
        add("")
    add("> *TODO (human): algebraic (SAT/Grobner/XL), cube, correlation, and "
        "distinguishing attack results with scaling curves (`scaling.pdf`).*")
    add("")

    # 5. Forward/backward security
    add("## 5. Forward/Backward Security")
    add("")
    if security is not None and security.get("state_update_bijective") is not None:
        add(f"- State update bijective: **{security['state_update_bijective']}**")
        add(f"- {security.get('backward_security_note', '')}")
        add("")
    else:
        add("> *TODO (human): bijectivity / one-wayness of the state update, "
            "resynchronization leakage.*")
        add("")

    # 6. Security argument (Tier 1/2) + post-quantum
    add("## 6. Security Argument and Post-Quantum Considerations")
    add("")
    if security is not None:
        pl = security.get("provable_checklist", {})
        if pl:
            add(f"- Construction type: **{pl.get('label', '')}**")
            add(f"- Route: {pl.get('route', '')}")
            add(f"- To prove: {', '.join(pl.get('to_prove', []))}")
            add("")
        if security.get("post_quantum_bits") is not None:
            add(f"- Post-quantum (Grover): {security.get('pq_note', '')}")
            add("")
    add("> *TODO (human): state the claims as PRG definitions and give the Tier 1 "
        "reduction or Tier 2 argument. Do not overclaim a reduction that does not exist.*")
    add("")

    # 7. Performance & comparison
    add("## 7. Performance and Comparison")
    add("")
    add("Reference ciphers (`comparison.csv/.tex`):")
    add("")
    add("| Cipher | Claimed (bits) | Best known attack | Status |")
    add("|---|---|---|---|")
    for e in REFERENCE_CIPHERS:
        add(f"| {e['cipher']} | {e['claimed_bits']} | {e['best_attack']} | {e['status']} |")
    add("")
    if fpga is not None:
        add(f"FPGA estimate (fixed clock {fpga.get('clock_mhz')} MHz): "
            f"{fpga.get('luts')} LUTs, {fpga.get('ffs')} FFs, "
            f"{fpga.get('throughput_mbps')} Mbit/s (rough model).")
        add("")

    # 8. Conclusion
    add("## 8. Conclusion")
    add("")
    add("> *TODO (human): summarize security margins and open problems.*")
    add("")

    path = os.path.join(outdir, "report.md")
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    return path
